steps:
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '-g', 'pnpm']
  - name: 'node:18'
    entrypoint: pnpm
    args: ['install']

  # Run tests
  - name: 'node:18'
    entrypoint: pnpm
    args: ['test:ci']

  - name: 'node:18'
    entrypoint: pnpm
    args: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/slack-opsgenie-bot', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/slack-opsgenie-bot']

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/slack-opsgenie-bot/'
    paths: ['dist/**']

images:
  - 'gcr.io/$PROJECT_ID/slack-opsgenie-bot'
