steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '-g', 'pnpm']
  - name: 'node:18'
    entrypoint: pnpm
    args: ['install']

  # Run tests
  - name: 'node:18'
    entrypoint: pnpm
    args: ['test:ci']

  # Build the application
  - name: 'node:18'
    entrypoint: pnpm
    args: ['build']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/slack-opsgenie-bot', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/slack-opsgenie-bot']

# Store artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/slack-opsgenie-bot/'
    paths: ['dist/**']

# Store Docker image
images:
  - 'gcr.io/$PROJECT_ID/slack-opsgenie-bot'
